// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHmqDvonXQ0Q06Wxyyfr1vPWk2kEnjU0s',
    appId: '1:1098873194803:web:c683feea3df0208dc55646',
    messagingSenderId: '1098873194803',
    projectId: 'face-recognition2303',
    authDomain: 'face-recognition2303.firebaseapp.com',
    databaseURL: 'https://face-recognition2303-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition2303.appspot.com',
    measurementId: 'G-DTM2J24LE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSc0syjW0AeWlJtpCxrrOrVVbocSkImA',
    appId: '1:1098873194803:android:4d75320e2a5ac847c55646',
    messagingSenderId: '1098873194803',
    projectId: 'face-recognition2303',
    databaseURL: 'https://face-recognition2303-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition2303.appspot.com',
  );

}