// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp6mef-kqW8YhT2sydWFLJHlQz4fwpnCM',
    appId: '1:1036963134991:web:42baec852bc1cf27a22d7a',
    messagingSenderId: '1036963134991',
    projectId: 'finalyear-codechamps',
    authDomain: 'finalyear-codechamps.firebaseapp.com',
    storageBucket: 'finalyear-codechamps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJiM0FdrH46f7jMSbbaN_2-6qBVQnSoZU',
    appId: '1:1036963134991:android:d7f5903a05c0d0d4a22d7a',
    messagingSenderId: '1036963134991',
    projectId: 'finalyear-codechamps',
    storageBucket: 'finalyear-codechamps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMoKCYNkKHQDNnw7SX-6bZtdbsjPu2HU',
    appId: '1:1036963134991:ios:8673d7e28b34ba22a22d7a',
    messagingSenderId: '1036963134991',
    projectId: 'finalyear-codechamps',
    storageBucket: 'finalyear-codechamps.firebasestorage.app',
    iosBundleId: 'com.example.finalYearCodechamps2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKMoKCYNkKHQDNnw7SX-6bZtdbsjPu2HU',
    appId: '1:1036963134991:ios:8673d7e28b34ba22a22d7a',
    messagingSenderId: '1036963134991',
    projectId: 'finalyear-codechamps',
    storageBucket: 'finalyear-codechamps.firebasestorage.app',
    iosBundleId: 'com.example.finalYearCodechamps2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp6mef-kqW8YhT2sydWFLJHlQz4fwpnCM',
    appId: '1:1036963134991:web:a149cd4fb77368a4a22d7a',
    messagingSenderId: '1036963134991',
    projectId: 'finalyear-codechamps',
    authDomain: 'finalyear-codechamps.firebaseapp.com',
    storageBucket: 'finalyear-codechamps.firebasestorage.app',
  );
}
